### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by Cobertos** [kei-ito/hexo-deployer-aws-s3#18]
Getting this error when deploying
```
$ hexo deploy
ERROR Plugin load failed: hexo-deployer-aws-s3
Error: EISDIR: illegal operation on a directory, read
ERROR Deployer not found: aws-s3
```

Config:
```
deploy:
  type: aws-s3
  region: us-east-2
  bucket: cobertos.com
```

I have also configured my `~/.aws/credentials` with the proper credentials

**Comment by kei-ito** [comment]
There was a mistake in CI configuration and `lib/*.js` files were not included in the package.

I've published [v0.3.5] that fixes this issue.
Thank you very much for your report.

[v0.3.5]: https://www.npmjs.com/package/hexo-deployer-aws-s3/v/0.3.5

**Comment by Cobertos** [comment]
Thank you so much, I'll update and try in a few hours/days

**Comment by Cobertos** [comment]
Yup, got this to work, thank you!
