### ISSUE TITLE
Not reading from ~/.aws/credentials file

### ISSUE THREAD

**Issue by acyuta108** [kei-ito/hexo-deployer-aws-s3#2]
`hexo deploy` does not read the credentials from the ~/.aws/credentials as specified in the docs. It only works with env variables.
Tried chmod'ing, didn't help.

**Comment by ziggythehamster** [comment]
Looking at the code, this deployer doesn't handle any of the AWS credential stuff. The AWS SDK does. Click the link in the README.md about setting up NodeJS. You probably need to specify `AWS_PROFILE` or something along those lines.

**Comment by kei-ito** [comment]
@ziggythehamster wrote what should I write here on my behalf. Thank you.
