### ISSUE TITLE
AWS Profile

### ISSUE THREAD

**Issue by oojacoboo** [kei-ito/hexo-deployer-aws-s3#67]
How do you define which AWS profile the deployer uses?

**Comment by oojacoboo** [comment]
Details on defining the profile with the AWS client: 
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-shared.html

**Comment by kei-ito** [comment]
There's the answer for your question in the document you shared.
>By default, the SDK checks the AWS_PROFILE environment variable to determine which profile to use. If the AWS_PROFILE variable is not set in your environment, the SDK uses the credentials for the [default] profile. To use one of the alternate profiles, set or change the value of the AWS_PROFILE environment variable. For example, given the configuration file shown above, to use the credentials from the work account, set the AWS_PROFILE environment variable to work-account (as appropriate for your operating system).

For example, you can `hexo publish` with `AWS_PROFILE=MyProfile` by this↓ command.
```
env AWS_PROFILE=MyProfile hexo publish
```

**Comment by oojacoboo** [comment]
Yep, I was actually just about to update this post with those details.  Thanks.

It'd be nice to have this in the docs.

**Comment by kei-ito** [comment]
This plugin leaves the handling of credentials to the aws-sdk. I don't want to incur the cost of syncing the documentation with the aws-sdk, so let me leave it at that.
